# Generated by Django 5.0.7 on 2024-08-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administartion', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=65)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_post', to='administartion.userprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_post', to='administartion.userprofile')),
            ],
        ),
    ]
