# Generated by Django 5.0.7 on 2025-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='exit', upload_to='blog-post-image'),
            preserve_default=False,
        ),
    ]
