# Generated by Django 5.0.7 on 2024-07-29 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administartion', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='administartion.userprofile')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to='administartion.userprofile')),
                ('pending_followers', models.ManyToManyField(blank=True, related_name='pending_followers', to='administartion.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administartion.userprofile')),
            ],
        ),
    ]
