import random


suggested_messages = random.choice([
    "Hello, how are you?",
    "What are your plans for the weekend?",
    "Have you seen the latest movie?",
    "Did you hear about the news?",
    "How's the weather today?",
    "Do you have any hobbies?",
    "Have you read any good books lately?",
    "What's your favorite type of music?",
    "Are you into sports?",
    "Do you like to travel?",
    "Have you tried any new restaurants recently?",
    "What's your favorite thing to do in your free time?",
    "Are you a morning person or a night owl?",
    "Do you prefer tea or coffee?",
    "What's the best vacation you've ever been on?",
    "What's your favorite season?",
    "Do you enjoy cooking?",
    "What's the last thing you binge-watched?",
    "Are you a cat person or a dog person?",
    "Do you like to exercise?",
    "What's your dream job?",
    "Do you have any pets?",
    "What's the most interesting place you've visited?",
    "What's your favorite holiday?",
    "Are you a planner or do you prefer to be spontaneous?",
    "What's your favorite type of cuisine?",
    "Do you have any siblings?",
    "What's your favorite movie genre?",
    "What's the best advice you've ever received?",
    "Do you prefer city life or countryside?",
    "What's your favorite type of dessert?",
    "Are you a morning person or a night owl?",
    "Do you have any hidden talents?",
    "What's the last concert you went to?",
    "Do you like to dance?",
    "What's your favorite board game?",
    "What's your favorite holiday tradition?",
    "Do you have any phobias?",
    "What's your favorite childhood memory?",
    "Do you enjoy hiking?",
    "What's your favorite type of art?",
    "Do you believe in ghosts?",
    "What's the last thing that made you laugh?",
    "Do you like to garden?",
    "What's your favorite type of pizza topping?",
    "What's your go-to karaoke song?",
    "Do you like to attend live events?",
    "What's your favorite way to relax?",
    "Do you enjoy DIY projects?",
    "What's the most memorable gift you've ever received?",
    "Do you like to attend festivals?",
    "What's your favorite quote?",
    "Do you enjoy stargazing?",
    "What's your favorite type of flower?",
    "Do you believe in aliens?",
    "What's your favorite type of book?",
    "Do you enjoy camping?",
    "What's your favorite outdoor activity?",
    "Do you like to attend parties?",
    "What's your favorite childhood TV show?",
    "Do you like to go fishing?",
    "What's your favorite ice cream flavor?",
    "Do you like to watch cooking shows?",
    "What's your favorite type of soup?",
    "Do you enjoy going to museums?",
    "What's your favorite type of candy?",
    "Do you like to go biking?",
    "What's your favorite type of sandwich?",
    "Do you enjoy attending workshops?",
    "What's your favorite type of fruit?",
    "Do you like to visit historical sites?",
    "What's your favorite type of pasta?",
    "Do you enjoy attending theater productions?",
    "What's your favorite type of cheese?",
    "Do you like to go for walks?",
    "What's your favorite way to spend a rainy day?",
    "Do you enjoy attending art exhibitions?",
    "What's your favorite type of cookie?",
    "Do you like to go skiing or snowboarding?",
    "What's your favorite type of chocolate?",
    "Do you enjoy visiting amusement parks?",
    "What's your favorite type of breakfast food?",
    "Do you like to go horseback riding?",
    "What's your favorite type of tea?",
    "Do you enjoy attending wine tastings?",
    "What's your favorite type of cocktail?",
    "Do you like to go sailing?",
    "What's your favorite type of coffee?",
    "Do you enjoy attending comedy shows?",
    "What's your favorite type of beer?",
    "Do you like to go kayaking?",
    "What's your favorite type of wine?",
    "Do you enjoy attending music festivals?",
    "What's your favorite type of whiskey?",
    "Do you like to go rock climbing?",
    "What's your favorite type of rum?",
    "Do you enjoy attending food festivals?",
    "What's your favorite type of vodka?",
    "Do you like to go scuba diving?",
    "What's your favorite type of gin?",
    "Do you enjoy attending film festivals?",
    "What's your favorite type of tequila?",
    "Do you like to go snorkeling?",
    "What's your favorite type of brandy?",
    "Do you enjoy attending cultural festivals?",
    "What's your favorite type of liqueur?",
    "Do you like to go skydiving?",
    "What's your favorite type of sake?",
    "Do you enjoy attending literary festivals?",
    "What's your favorite type of cider?",
    "Do you like to go bungee jumping?",
    "What's your favorite type of absinthe?"
])